name: Delete old workflow runs
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
  watch:
    types: started

jobs:
  del_runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 0
